# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2024-02-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='theme', max_length=255)),
                ('message', models.CharField(default='message', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email', max_length=255)),
                ('first_name', models.CharField(default='first_name', max_length=255)),
                ('last_name', models.CharField(default='last_name', max_length=255)),
                ('birthday', models.DateField(default='birthday', max_length=255)),
            ],
        ),
    ]
