# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2024-02-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_scheduledmailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmailing',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
