# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2024-02-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_scheduledmailing_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmailing',
            name='sent',
        ),
        migrations.AddField(
            model_name='scheduledmailing',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
